"""init data

Revision ID: ee2ecfc80076
Revises: 
Create Date: 2026-05-14 13:45:12.071454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee2ecfc80076'  # 🔥 ОБЯЗАТЕЛЬНО
down_revision: Union[str, None] = None  # 🔥 ОБЯЗАТЕЛЬНО
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connection',
    sa.Column('dt', sa.DateTime(), nullable=False),
    sa.Column('well_id', sa.String(length=100), nullable=False),
    sa.Column('i', sa.Integer(), nullable=False),
    sa.Column('j', sa.Integer(), nullable=False),
    sa.Column('k', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.String(length=100), nullable=False),
    sa.Column('swl', sa.REAL(), nullable=True),
    sa.Column('swu', sa.REAL(), nullable=True),
    sa.CheckConstraint('i >= 0 AND i <= 65535', name='chk_conn_i'),
    sa.CheckConstraint('j >= 0 AND j <= 65535', name='chk_conn_j'),
    sa.CheckConstraint('k >= 0 AND k <= 65535', name='chk_conn_k'),
    sa.PrimaryKeyConstraint('dt', 'well_id', 'i', 'j', 'k', 'test_id'),
    schema='data'
    )
    op.create_index('idx_data_conn_lookup', 'connection', ['dt', 'well_id', 'test_id'], unique=False, schema='data')
    op.create_table('field_tests',
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('test_id', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('field_name', 'test_id'),
    schema='data'
    )
    op.create_index('field_name', 'field_tests', ['test_id'], unique=False, schema='data')
    op.create_table('group',
    sa.Column('dt', sa.DateTime(), nullable=False),
    sa.Column('group_id', sa.String(length=100), nullable=False),
    sa.Column('test_id', sa.String(length=100), nullable=False),
    sa.Column('geff', sa.REAL(), nullable=True),
    sa.PrimaryKeyConstraint('dt', 'group_id', 'test_id'),
    schema='data'
    )
    op.create_index('idx_data_group_lookup', 'group', ['dt', 'group_id', 'test_id'], unique=False, schema='data')
    op.create_table('well',
    sa.Column('dt', sa.DateTime(), nullable=False),
    sa.Column('well_id', sa.String(length=100), nullable=False),
    sa.Column('test_id', sa.String(length=100), nullable=False),
    sa.Column('weff', sa.REAL(), nullable=True),
    sa.PrimaryKeyConstraint('dt', 'well_id', 'test_id'),
    schema='data'
    )
    op.create_index('idx_data_well_lookup', 'well', ['dt', 'well_id', 'test_id'], unique=False, schema='data')
    op.create_table('connection',
    sa.Column('dt', sa.DateTime(), nullable=False),
    sa.Column('well_id', sa.String(length=100), nullable=False),
    sa.Column('i', sa.Integer(), nullable=False),
    sa.Column('j', sa.Integer(), nullable=False),
    sa.Column('k', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.String(length=100), nullable=False),
    sa.Column('cgpr', sa.REAL(), nullable=True),
    sa.Column('cgpt', sa.REAL(), nullable=True),
    sa.Column('cwpr', sa.REAL(), nullable=True),
    sa.Column('cwpt', sa.REAL(), nullable=True),
    sa.Column('cbp', sa.REAL(), nullable=True),
    sa.CheckConstraint('i >= 0 AND i <= 65535', name='chk_unsumry_i'),
    sa.CheckConstraint('j >= 0 AND j <= 65535', name='chk_unsumry_j'),
    sa.CheckConstraint('k >= 0 AND k <= 65535', name='chk_unsumry_k'),
    sa.PrimaryKeyConstraint('dt', 'well_id', 'i', 'j', 'k', 'test_id'),
    schema='unsumry'
    )
    op.create_index('idx_unsumry_conn_lookup', 'connection', ['dt', 'well_id', 'test_id'], unique=False, schema='unsumry')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_unsumry_conn_lookup', table_name='connection', schema='unsumry')
    op.drop_table('connection', schema='unsumry')
    op.drop_index('idx_data_well_lookup', table_name='well', schema='data')
    op.drop_table('well', schema='data')
    op.drop_index('idx_data_group_lookup', table_name='group', schema='data')
    op.drop_table('group', schema='data')
    op.drop_index('field_name', table_name='field_tests', schema='data')
    op.drop_table('field_tests', schema='data')
    op.drop_index('idx_data_conn_lookup', table_name='connection', schema='data')
    op.drop_table('connection', schema='data')
    # ### end Alembic commands ###